<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chirp.Core\Chirp.Core.csproj" />
    </ItemGroup>

</Project>