
name: Publish

on:
  push:
    tags:
      - "v*.*.*"
        
permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.304
          
      - name: Build
        shell: bash
        run: |
            tag=$(git describe --tags --abbrev=0)
            
            dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net9.0 --os win -c Release -o "App-$tag-windows"
            dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net9.0 --os linux -c Release -o "App-$tag-linux"
            dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net9.0 --os osx -c Release -o "App-$tag-macos"
            
            7z a -tzip "App-$tag-windows.zip" "App-$tag-windows/*"
            7z a -tzip "App-$tag-linux.zip" "App-$tag-linux/*"
            7z a -tzip "App-$tag-macos.zip" "App-$tag-macos/*"
            
            rm -r "App-$tag-windows"
            rm -r "App-$tag-linux"
            rm -r "App-$tag-macos"
            
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}